// src/lib/components/ui/GlassElement/GlassElement.svelte
<script lang="ts">
  import {
    getDisplacementFilter,
    type DisplacementOptions,
  } from './getDisplacementFilter';
  import { getDisplacementMap } from './getDisplacementMap';
  import './GlassElement.css';

  export let height!: number;
  export let width!: number;
  export let depth!: number;
  export let radius!: number;
  export let strength!: number;
  export let chromaticAberration!: number;
  export let blur: number = 2;
  export let debug: boolean = false;

  let clicked = false;

  // whenever clicked or depth change, recompute actualDepth
  $: actualDepth = depth / (clicked ? 0.7 : 1);

  // recompute the backdrop-filter URL when inputs change
  $: filterUrl = getDisplacementFilter({
    height,
    width,
    radius,
    depth: actualDepth,
    strength,
    chromaticAberration,
  });

  // recompute the displacement‐map URL when needed
  $: mapUrl = getDisplacementMap({
    height,
    width,
    radius,
    depth: actualDepth,
  });

  // build the style string
  $: styleString = debug
    ? `
      height: ${height}px;
      width: ${width}px;
      border-radius: ${radius}px;
      background: url("${mapUrl}");
      box-shadow: none;
    `
    : `
      height: ${height}px;
      width: ${width}px;
      border-radius: ${radius}px;
      backdrop-filter:
        blur(${blur / 2}px)
        url('${filterUrl}')
        blur(${blur}px)
        brightness(1.1)
        saturate(1.5);
    `;
</script>

<div
  class="box"
  style={styleString}
  on:mousedown={() => (clicked = true)}
  on:mouseup={() => (clicked = false)}
>
  <slot />
</div>

// src/lib/components/ui/GlassElement/GlassElement.tsx
// All credit goes to the original author
// https://medium.com/ekino-france/liquid-glass-in-css-and-svg-839985fcb88d


import { CSSProperties, ReactNode, useState } from "react";
import {
  getDisplacementFilter,
  DisplacementOptions,
} from "./getDisplacementFilter";
import { getDisplacementMap } from "./getDisplacementMap";
import styles from "./GlassElement.module.css";

type GlassElementProps = DisplacementOptions & {
  children?: ReactNode | undefined;
  blur?: number;
  debug?: boolean;
};

export const GlassElement = ({
  height,
  width,
  depth: baseDepth,
  radius,
  children,
  strength,
  chromaticAberration,
  blur = 2,
  debug = false,
}: GlassElementProps) => {
  /* Change element depth on click */
  const [clicked, setClicked] = useState(false);
  let depth = baseDepth / (clicked ? 0.7 : 1);

  /* Dynamic CSS properties */
  const style: CSSProperties = {
    height: `${height}px`,
    width: `${width}px`,
    borderRadius: `${radius}px`,
    backdropFilter: `blur(${blur / 2}px) url('${getDisplacementFilter({
      height,
      width,
      radius,
      depth,
      strength,
      chromaticAberration,
    })}') blur(${blur}px) brightness(1.1) saturate(1.5) `,
  };

  /* Debug mode: display the displacement map instead of actual effect */
  if (debug === true) {
    style.background = `url("${getDisplacementMap({
      height,
      width,
      radius,
      depth,
    })}")`;
    style.boxShadow = "none";
  }
  return (
    <div
      className={styles.box}
      style={style}
      onMouseDown={() => setClicked(true)}
      onMouseUp={() => setClicked(false)}
    >
      {children}
    </div>
  );
};
